name: Update Xunyi Data
permissions:
  contents: write

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip install pandas requests

      - name: 运行数据采集
        env:
          XUNYI_TOKEN: ${{ secrets.XUNYI_TOKEN }}
        run: python collect_data.py

      - name: 提交数据更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git reset
          git add xunyi_likes_summary.csv
          git diff --cached --quiet || git commit -m "auto update data"
          git push
